#utilze: "$dir_profile/wpa0"
#GENERATOR/generate_wpa_profile.sh

set -o nounset
set +e
clear
echo wish:  Successfully initialized wpa_supplicant
echo 
#echo example: wpa_supplicant -Dnl80211 -iwlan0 -c/etc/wpa_supplicant.conf

#file="/tmp/wpa0" # generated by generate_wpa_profile.sh 
$dir_parent/GENERATOR/wpa2.sh

file1="FIX/rf_kill.cfg"
assert file_exist "$file1"
cat1 $file1 true
( commander "source $file1" )

file="/tmp/wpa0"
assert file_exist "$file"
commander "sudo wpa_supplicant  -D$driver -i$device -c$file"



